version: 0.2
phases:
  build:
    commands:
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin
      - sam build -t template.yaml
      - aws cloudformation package --template-file .aws-sam/build/template.yaml --s3-bucket mj-sam-test --output-template-file cloudformation-packaged.yaml
      - aws s3 cp ./cloudformation-packaged.yaml mj-sam-test/cloudformation-packaged.yaml   
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml